"""Add enterprise workspace models

Revision ID: 45410af14e89
Revises: 6044976e7911
Create Date: 2026-06-28 14:26:41.930921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45410af14e89'
down_revision: Union[str, Sequence[str], None] = '6044976e7911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_workspace_snapshots_creator_id_users'), 'users', ['creator_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_workspace_snapshots_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_workspace_snapshots_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_workspace_snapshots_creator_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
