"""AddActivityTable

Revision ID: 6044976e7911
Revises: 2bfbd5808fcb
Create Date: 2026-06-27 19:08:35.520349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6044976e7911'
down_revision: Union[str, Sequence[str], None] = '2bfbd5808fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_category', 'activities', ['category'], unique=False)
    op.create_index('ix_activities_created_at', 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index('ix_activities_type', 'activities', ['type'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_type', table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index('ix_activities_created_at', table_name='activities')
    op.drop_index('ix_activities_category', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
